// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daxdgiqwozaujudmmyyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheGRnaXF3b3phdWp1ZG1teXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTk2MzUsImV4cCI6MjA2NTk3NTYzNX0.DjjbaIfaWylAoHrPURlmE2l_F2t0kxzPZJN6BI7FW3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);